spring.application.name=sport

#spring.datasource.url=jdbc:h2:mem:eventDB
spring.datasource.url=jdbc:h2:file:./data/eventDB

spring.datasource.username=Jonas
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

# Aktiviert die Unterscheidung per URL-Parameter
spring.mvc.contentnegotiation.favor-parameter=true
# Definiert den Namen des Parameters (Standard ist oft 'format')
spring.mvc.contentnegotiation.parameter-name=format

# hidden methods ermöglicht auch alle CRUD-Operationen im HTML-Controller verwenden zu können
# Standardmäßig versteht der Browser in HTML nur Get und Post
spring.mvc.hiddenmethod.filter.enabled=true
